apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  labels:
    app: kaniko
  namespace: jenkins
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - sleep
    args:
      - "999999"
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    - name: workspace
      mountPath: /workspace
  - name: git
    image: alpine/git:latest
    command:
      - sleep
    args:
      - "999999"
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockerhub-secret
  - name: workspace
    emptyDir: {}

# test1234